### PR TITLE
Fixed #324 - Switched slowparse to submodules from npm modules

### LINKED ISSUE #324: Replace extension dependencies in `node_modules` with submodule equivalents
Is the Travis/Gruntfile build stuff not doing the right thing, and missing deps?

```
GET https://mozillathimblelivepreview.net/bramble/node_modules/slowparse/locale/en_US.json 404
GET "https://mozillathimblelivepreview.net/bramble/node_modules/slowparse/locale/en_US.json".text.get
[Extension] failed to load /bramble/dist/extensions/extra/HTMLHinter - Error: /bramble/dist/extensions/extra/HTMLHinter/../../../../node_modules/slowparse/locale/en_US.json HTTP status: 404
```

### PR DESCRIPTION
**Pull request by sedge**

### CODE REVIEW

File: src/extensions/extra/HTMLHinter/parser.js [hunk 1]
```diff
@@ -5,8 +5,8 @@ define(function(require) {
     "use strict";
 
     // Requires an `npm install` from root
-    var slowparse = require("../../../../node_modules/slowparse/slowparse");
-    var errorMessages = require("text!../../../../node_modules/slowparse/locale/en_US.json");
+    var slowparse = require("../../../thirdparty/slowparse/slowparse");
```
Comment (gideonthomas) [inline src/extensions/extra/HTMLHinter/parser.js]: `brackets.getModule` instead?

Comment (sedge) [inline src/extensions/extra/HTMLHinter/parser.js]: No, because slowparse isn't being loaded anywhere else first. As I understand it, a module must be `require()`'d before it can be retrieved with `getModule`

**Comment by gideonthomas** [comment]
ok r+ then

File: src/extensions/extra/HTMLHinter/parser.js (hunk 1 above)
Comment (humphd) [inline src/extensions/extra/HTMLHinter/parser.js]: Correct, and we don't need to load it in the `src/` Brackets require context.

**Comment by humphd** [comment]
r+ with travis and local testing (I'm only reading the code).

File: .gitmodules [hunk 2]
```diff
@@ -40,3 +40,6 @@
 [submodule "src/thirdparty/marked"]
 	path = src/thirdparty/marked
 	url = https://github.com/chjj/marked.git
+[submodule "src/thirdparty/slowparse"]
+	path = src/thirdparty/slowparse
+	url = git@github.com:mozilla/slowparse.git
```
Comment (sedge) [inline .gitmodules]: Bah, this should be HTTPS
