### PR TITLE
Fix #352: deal with encoded paths, preload blob urls, fix fs bugs

### LINKED ISSUE #352: Use project root when saving dropped files
We are still writing to the root vs. the project root dir.

### PR DESCRIPTION
**Pull request by humphd**
I ended up finding a bunch of bad bugs while fixing this original issue:

* added way to update the startup project root (we don't have a caller yet, we'll have to do that when the project name changes)
* dealt with Brackets encoding filenames when they are used as URLs (affects names with spaces, special characters)
* added preloading for blob urls on startup so any existing items in the filesystem have blog urls when you need them (e.g., clicking on an image you dragged in last time)
* update the filetree view after we save the selfie, so the file shows
* fix paths for selfie and drag and drop to use project root vs. /
* fixed a rename bug, where blob urls didn't change (there's another bug I need to file for the case that we rename a dir--all the children need their blob url paths updated)
* fixed a bug in readFile, when options wasn't passed.

### CODE REVIEW

File: src/filesystem/impls/filer/BlobUtils.js [hunk 1]
```diff
@@ -89,6 +95,8 @@ define(function (require, exports, module) {
     // Support sync and async calls to the URL cache. Also check to see
     // if async calls can by run immediately regardless (i.e., no disk access).
     function getUrl(filename, maybeCallback) {
+        filename = decodePath(filename);
```
Comment (gideonthomas) [inline src/filesystem/impls/filer/BlobUtils.js]: Shouldn't we also `decodePath` in the `_getUrlAsync` function?

**Comment by gideonthomas** [comment]
This looks good to me! r+
